Passes status of scenario and failed reason
jonsamwell/dart_gherkin pull request #59
Opened 2022-05-03 18:07 UTC by AFASbart

For the flutter_gherkin package I have added the possibility to pass along the scenario's final status and to retry a specific step multiple times.

2022-05-03 18:11 UTC, AFASbart commented
@jonsamwell Do you have the time to check this PR so we can resolve 3 (!) issues on the flutter_gherkin branch?

2022-05-04 06:49 UTC, jonsamwell requested changes

2022-05-04 06:49 UTC, jonsamwell commented on lib/src/configuration.dart
> +  int stepMaxRetries = 3;
We should add documentation to this parameter.  Just something short.  I actually think this should default to zero to preserve existing behaviour.  It is actually bad practice to retry.  With cucumberjs to have to be explicit about the number of retries for a step / scenario

2022-05-04 06:49 UTC, jonsamwell commented on lib/src/gherkin/steps/step_definition.dart
> +      return ErroredStepResult(elapsedMilliseconds, StepExecutionResult.error,
Add trailing comma and new line

2022-05-04 07:00 UTC, AFASbart commented
Before merging, can you recheck the flutter PR: https://github.com/jonsamwell/flutter_gherkin/pull/221. The max retries need to be atleast 1 ofcourse (so I added a + 1 on the for loop) and I have added a delay after each failed attempt.

2022-05-04 07:05 UTC, jonsamwell approved these changes

2022-05-06 11:55 UTC, merged